# Generated by Django 4.2.6 on 2023-11-22 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search_station',
            fields=[
                ('station_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Search_train',
            fields=[
                ('train_no', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('hault', models.IntegerField()),
                ('arrival_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_no', models.IntegerField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=11)),
                ('destination', models.CharField(max_length=20)),
                ('arrival_time', models.TimeField()),
                ('dep_time', models.TimeField()),
                ('avail_seats', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=34)),
                ('adhaar', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('city', models.CharField(max_length=11)),
                ('state', models.CharField(max_length=15)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Train_status',
            fields=[
                ('train_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='train2.train')),
                ('a_seats1', models.IntegerField()),
                ('a_seats2', models.IntegerField()),
                ('a_seats3', models.IntegerField()),
                ('b_seats1', models.IntegerField()),
                ('b_seats2', models.IntegerField()),
                ('b_seats3', models.IntegerField()),
                ('w_seats1', models.IntegerField()),
                ('w_seats2', models.IntegerField()),
                ('w_seats3', models.IntegerField()),
                ('flare1', models.FloatField(max_length=11)),
                ('flare2', models.FloatField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=11)),
                ('no_of_passenger', models.IntegerField()),
                ('train_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='train2.train')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='train2.user')),
            ],
        ),
        migrations.CreateModel(
            name='Stops_at',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('station_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='train2.station')),
                ('train_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='train2.train')),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='train_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='train2.train'),
        ),
        migrations.CreateModel(
            name='Reaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('station_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='train2.station')),
                ('train_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='train2.train')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pnr', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=11)),
                ('reservation_status', models.CharField(max_length=20)),
                ('seat_no', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('ticket_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='train2.train')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='train2.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='train2.passenger')),
                ('ticket_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='train2.ticket')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='train2.user')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='train2.ticket')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='train2.user')),
            ],
        ),
        migrations.CreateModel(
            name='Starts',
            fields=[
                ('train_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='train2.train')),
                ('station_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='train2.station')),
            ],
        ),
    ]
