# Generated by Django 4.2.6 on 2023-11-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaches',
            name='time',
            field=models.TimeField(),
        ),
    ]
