# Generated by Django 4.2.6 on 2023-11-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train2', '0003_alter_reaches_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaches',
            name='time',
            field=models.TimeField(),
        ),
    ]
