# Generated by Django 4.2.6 on 2023-11-23 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('train2', '0005_alter_reaches_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaches',
            name='arrival_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reaches',
            name='dep_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
