# Generated by Django 4.2.6 on 2023-11-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train2', '0006_reaches_arrival_time_reaches_dep_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_station', models.CharField(max_length=20)),
                ('second_station', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Search_station',
        ),
        migrations.DeleteModel(
            name='Search_train',
        ),
    ]
