# Generated by Django 4.2.6 on 2023-11-24 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('train2', '0007_duration_delete_search_station_delete_search_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='duration',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
