# Generated by Django 4.2.6 on 2023-11-24 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train2', '0009_distance_delete_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distance',
            old_name='first_station',
            new_name='station_name',
        ),
        migrations.RemoveField(
            model_name='distance',
            name='second_station',
        ),
        migrations.AddField(
            model_name='distance',
            name='train_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='train2.train'),
        ),
    ]
