# Generated by Django 4.2.6 on 2023-11-24 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('train2', '0010_rename_first_station_distance_station_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='distance',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Distance',
        ),
    ]
