# Generated by Django 4.2.6 on 2023-11-24 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train2', '0011_station_distance_delete_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stops_at',
            name='time',
        ),
    ]
