# Generated by Django 4.2.6 on 2023-11-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train2', '0012_remove_stops_at_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='source',
            field=models.CharField(max_length=20),
        ),
    ]
