# Generated by Django 4.2.6 on 2023-11-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train2', '0013_alter_train_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='arrival_time',
        ),
    ]
