# Generated by Django 4.2.6 on 2023-11-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train2', '0016_remove_station_arrival_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('number', models.CharField(max_length=10)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
