# Generated by Django 4.2.6 on 2023-11-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train2', '0017_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaches',
            name='arrival_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reaches',
            name='dep_time',
            field=models.TimeField(null=True),
        ),
    ]
